.TH "Collisionspheren" 3 "Sun May 9 2021" "Version 1.42.14_wf" "MCDC_simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Collisionspheren \- \fBCollision\fP Final class ============================================================================/\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <collisionsphere\&.h>\fP
.SH "Detailed Description"
.PP 
\fBCollision\fP Final class ============================================================================/\&. 

Class to implement spherical bounding boxes for the WALKER mean diffusion\&. This class provides methods in order to create and update spherical bounding boxes used to compute the collisions\&. 
.PP
\fBAuthor:\fP
.RS 4
Jonathan Rafael 
.SH "February 2017 "
.PP
.RE
.PP
.PP
Father class\&. this class provides methods in order to create and update spherical bounding box used to compute the collisions\&. The implementation is based on two collision spheres\&. The inner one (small) and the (outer)\&. The fist saves the objects where th particle MAY collide in a given time, While the second saves the full set of obstacles where the particle can possibly collide, i\&.e\&. that are physically achievable for the walker to collide\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for MCDC_simulator from the source code\&.
