.TH "Collisionsphere" 3 "Sun May 9 2021" "Version 1.42.14_wf" "MCDC_simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Collisionsphere
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBCylinderCollisionSphere\fP, and \fBPLYCollisionSphere\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBbig_sphere_distance\fP"
.br
.ti -1c
.RI "float \fBsmall_sphere_distance\fP"
.br
.ti -1c
.RI "unsigned \fBlist_size\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "float Collisionsphere::big_sphere_distance"
Size of the big (outer) collision sphere 
.SS "float Collisionsphere::small_sphere_distance"
Size of the small (inner) collision sphere 

.SH "Author"
.PP 
Generated automatically by Doxygen for MCDC_simulator from the source code\&.
