.TH "Propagator" 3 "Sun May 9 2021" "Version 1.42.14_wf" "MCDC_simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Propagator
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitPropagator\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint \fBnum_dirs\fP =0"
.br
.ti -1c
.RI "uint \fBnum_times\fP = 0"
.br
.ti -1c
.RI "Eigen::Matrix3Xf \fBdirections\fP"
.br
.ti -1c
.RI "std::vector< unsigned > \fBlog_times\fP"
.br
.ti -1c
.RI "std::vector< std::vector< float > > \fBpropagator_log\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for MCDC_simulator from the source code\&.
