.TH "Sentinels" 3 "Sun May 9 2021" "Version 1.42.14_wf" "MCDC_simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sentinels \- \fBCollision\fP Final class ====================================================================/\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sentinel\&.h>\fP
.SH "Detailed Description"
.PP 
\fBCollision\fP Final class ====================================================================/\&. 

Auxiliar class to check error and misbehaviours during the particle dynamics\&. 
.PP
\fBAuthor:\fP
.RS 4
Jonathan Rafael 
.RE
.PP
\fBDate:\fP
.RS 4
Junes 2017 
.PP
.RE
.PP
Class used to check the possible numerical errors or un-handed cases inside the dynamic simulation\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for MCDC_simulator from the source code\&.
